Handle buttons task list
Catalin12/to-do-ui pull request #7
Opened 2022-08-25 15:01 UTC by Catalin12

2022-08-25 15:19 UTC, danielursu requested changes

2022-08-25 15:19 UTC, danielursu commented on src/app/shared/click-type.enum.ts
> +export enum ClickTypeEnum {
```suggestion
export enum FormTypeEnum {
```

2022-08-25 15:19 UTC, danielursu commented on src/app/shared/click-type.enum.ts
> +	NULL = "Null"
```suggestion
```

2022-08-25 15:19 UTC, danielursu commented on src/app/task-form/task-form.component.ts
> +	public clickType = this.dialogService;
what is clickType?

2022-08-25 15:19 UTC, danielursu commented on src/app/task/task.component.ts
> +	public changeStatus = new EventEmitter<number>();
```suggestion
	public onChangeStatus = new EventEmitter<number>();
```

2022-08-25 15:19 UTC, danielursu commented on src/app/task/task.component.ts
> +	public clickDelete = new EventEmitter<number>();
```suggestion
	public onDelete = new EventEmitter<number>();
```

2022-08-25 15:19 UTC, danielursu commented on src/app/app.module.ts
>  import { ReactiveFormsModule } from "@angular/forms";
please resolve conflicts

2022-08-25 21:17 UTC, Catalin12 commented on src/app/task-form/task-form.component.ts
> +	public clickType = this.dialogService;
from past tests, I forgot to delete it

2022-08-26 07:27 UTC, carmina-c commented on src/app/app.module.ts
> +    InputTextModule,
tab here

2022-08-26 07:28 UTC, carmina-c approved these changes

2022-08-26 07:40 UTC, merged